package com.mammen.main;

import java.util.ArrayList;
import java.util.List;

import jaci.pathfinder.Pathfinder;
import jaci.pathfinder.Trajectory;
import jaci.pathfinder.Trajectory.Config;
import jaci.pathfinder.Trajectory.FitMethod;
import jaci.pathfinder.Waypoint;
import jaci.pathfinder.modifiers.SwerveModifier;
import jaci.pathfinder.modifiers.TankModifier;


public class ProfileGenerator 
{
	public enum DriveBase {
        TANK,
        SWERVE
    }

    public enum Units {
        IMPERIAL,
        METRIC
    }
    
    private double timeStep;
    private double velocity;
    private double acceleration;
    private double jerk;
    private double wheelBaseW;
    private double wheelBaseD;
    
    private DriveBase driveBase;
    private FitMethod fitMethod;
    private Units units;
    
    private final List<Waypoint> POINTS;
    
    // Trajectories for both bases
    // Use front-left and front-right for tank drive L and R
    private Trajectory fl;
    private Trajectory fr;
    private Trajectory bl;
    private Trajectory br;
    
    // Source trajectory
    // i.e. the center trajectory
    private Trajectory source;
    
    public ProfileGenerator()
    {
    	POINTS = new ArrayList<>();
    	resetValues();
    }
    
    /**
     * Resets configuration to default values
     */
    public void resetValues() 
    {
        timeStep = 0.05;
        velocity = 4;
        acceleration = 3;
        jerk = 60;
        wheelBaseW = 1.464;
        wheelBaseD = 0;

        fitMethod = FitMethod.HERMITE_CUBIC;
        driveBase = DriveBase.TANK;
        units = Units.IMPERIAL;
    }
    
    /**
     * Adds a waypoint to the list of waypoints
     *
     * @param x     the x-location of the waypoint
     * @param y     the y-location of the waypoint
     * @param angle the angle of direction at the point, in radians
     */
    public void addPoint( double x, double y, double angle ) 
    {
        POINTS.add(new Waypoint(x, y, angle));
    }
    
    /**
     * Adds a waypoint to the list of waypoints
     *
     * @param index the index of the waypoint to edit
     * @param x     the x-location of the waypoint
     * @param y     the y-location of the waypoint
     * @param angle the angle of direction at the point, in radians
     */
    public void editWaypoint( int index, double x, double y, double angle )
    {
        POINTS.get(index).x = x;
        POINTS.get(index).y = y;
        POINTS.get(index).angle = angle;
    }
    
    public void removePoint(int index) {
        POINTS.remove(index);
    }

    public int getNumWaypoints()
    {
        return POINTS.size();
    }

    /**
     * Clears all the existing waypoints in the list.
     * This also clears all trajectories generated by the waypoints.
     */
    public void clearPoints() 
    {
        POINTS.clear();

        fl = null;
        fr = null;
        bl = null;
        br = null;
    }
    
    /**
     * Updates the trajectories
     */
    public void updateTrajectories() throws Pathfinder.GenerationException 
    {
        Config config = new Config( fitMethod, Config.SAMPLES_HIGH, timeStep, velocity, acceleration, jerk );
        source = Pathfinder.generate( POINTS.toArray(new Waypoint[1]), config );

        if (driveBase == DriveBase.SWERVE) 
        {
            SwerveModifier swerve = new SwerveModifier(source);

            // There is literally no other swerve mode other than the default can someone please explain this to me
            swerve.modify( wheelBaseW, wheelBaseD, SwerveModifier.Mode.SWERVE_DEFAULT );

            fl = swerve.getFrontLeftTrajectory();
            fr = swerve.getFrontRightTrajectory();
            bl = swerve.getBackLeftTrajectory();
            br = swerve.getBackRightTrajectory();
        } 
        else  // By default, treat everything as tank drive.
        {
            TankModifier tank = new TankModifier(source);
            tank.modify(wheelBaseW);

            fl = tank.getLeftTrajectory();
            fr = tank.getRightTrajectory();
            bl = null;
            br = null;
        }
    }
    
    
    public double getTimeStep()
    {
        return timeStep;
    }

    public void setTimeStep(double timeStep)
    {
        this.timeStep = timeStep;
    }

    public double getVelocity() 
    {
        return velocity;
    }

    public void setVelocity(double velocity)
    {
        this.velocity = velocity;
    }

    public double getAcceleration() 
    {
        return acceleration;
    }

    public void setAcceleration(double acceleration) 
    {
        this.acceleration = acceleration;
    }

    public DriveBase getDriveBase()
    {
        return driveBase;
    }

    public void setDriveBase(DriveBase driveBase)
    {
        this.driveBase = driveBase;
    }

    public FitMethod getFitMethod()
    {
        return fitMethod;
    }

    public void setFitMethod(FitMethod fitMethod)
{
        this.fitMethod = fitMethod;
    }

    public Units getUnits()
    {
        return units;
    }

    public void setUnits(Units units)
    {
        this.units = units;
    }

    public double getJerk()
    {
        return jerk;
    }

    public void setJerk(double jerk) 
    {
        this.jerk = jerk;
    }

    public double getWheelBaseW() 
    {
        return wheelBaseW;
    }

    public void setWheelBaseW(double wheelBaseW)
    {
        this.wheelBaseW = wheelBaseW;
    }

    public double getWheelBaseD() {
        return wheelBaseD;
    }

    public void setWheelBaseD(double wheelBaseD)
    {
        this.wheelBaseD = wheelBaseD;
    }

    public List<Waypoint> getWaypointsList()
    {
        return POINTS;
    }

    public Trajectory getSourceTrajectory()
    {
        return source;
    }

    public Trajectory getFrontLeftTrajectory() 
    {
        return fl;
    }

    public Trajectory getFrontRightTrajectory() 
    {
        return fr;
    }

    public Trajectory getBackLeftTrajectory() 
    {
        return bl;
    }

    public Trajectory getBackRightTrajectory() 
    {
        return br;
    }
}










